---
- hosts: all
  become: yes
  remote_user: root # If you are a sudoer without access to root, put your username here!
  handlers:
    - import_tasks: handlers/main.yml
  tasks:
  - include_vars: dir=defaults
  - import_tasks: tasks/nginx.yaml
  - name: Add non-standard repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
      - deb http://ftp.debian.org/debian jessie-backports main
      - deb https://matrix.org/packages/debian/ jessie main
      - deb-src https://matrix.org/packages/debian/ jessie main
  - name: Add apt-key for jessie-backports
    apt_key:
      keyserver: pgpkeys.mit.edu
      id: "{{ item }}"
    with_items:
      - 8B48AD6246925553
      - 7638D0442B90D010
  - name: Add an apt signing key
    apt_key:
      url: https://matrix.org/packages/debian/repo-key.asc
      state: present
  - include_tasks: tasks/apt_upgrade.yml

  - name: Install requirements
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - lsof
      - curl
      - python
      - python-pip
  - name: Install requirements from jessie-backports
    apt:
      name: "{{ item }}"
      state: present
      default_release: jessie-backports
    with_items:
      - python-cffi
      - certbot

  - name: Set Debconf values for matrix-synapse
    debconf:
      name: matrix-synapse
      question: "{{item.question}}"
      value: "{{ item.value }}"
      vtype: "{{ item.vtype }}"
    with_items:
      - {question: 'matrix-synapse/report-stats',value: '{{ reportStats }}',vtype: 'boolean' }
      - {question: 'matrix-synapse/server-name',value: '{{ hostname }}',vtype: 'string' }

  - name: Install matrix-synapse
    apt: pkg=matrix-synapse state=present
    notify: restart matrix-synapse

  - name: Set Synapse Cache Factor
    lineinfile:
      path: /etc/default/matrix-synapse
      regexp: SYNAPSE_CACHE_FACTOR
      state: present
      line: "SYNAPSE_CACHE_FACTOR={{ SynapseCacheFactor }}"
    notify: restart matrix-synapse

  - name: Change enable_registration state
    lineinfile:
      path: /etc/matrix-synapse/homeserver.yaml
      regexp: "enable_registration: False"
      state: present
      line: "enable_registration: {{ enableRegistration }}"
    notify: restart matrix-synapse
