---
  - name: Install Nginx
    apt: pkg=nginx state=present
  - name: Copy nginx.conf to server
    copy:
      src: "{{ matrixConfFileToSend }}"
      dest: "/etc/nginx/sites-available/{{ hostname }}"
    notify:
      - restart nginx
  - name: Changes in nginx.conf
    lineinfile:
      path: /etc/nginx/sites-available/{{ hostname }}
      regexp: "{{ item.regexp }}"
      state: present
      line: "{{ item.line }}"
    with_items:
      - {regexp: 'server_name my.site.com;', line: '    server_name {{ hostname }}'}
      - {regexp: 'ssl_certificate     /etc/letsencrypt/live/my.site.com/fullchain.pem;', line: '    ssl_certificate     /etc/letsencrypt/live/{{ hostname }}/fullchain.pem;'}
      - {regexp: 'ssl_certificate_key /etc/letsencrypt/live/my.site.com/privkey.pem;', line: '    ssl_certificate_key /etc/letsencrypt/live/{{ hostname }}/privkey.pem;'}
    notify:
      - restart nginx
  - name: Clean sites-enabled/
    file:
      state: absent
      path: "/etc/nginx/sites-enabled/{{ item }}"
    with_items:
      - "{{ hostname }}"
      - default
  - name: Link sites-available to sites-enabled
    file:
      src: "/etc/nginx/sites-available/{{ hostname }}"
      dest: "/etc/nginx/sites-enabled/{{ hostname }}"
      state: link
    notify: restart nginx
  - import_tasks: certs.yml
