---
  - name: Install Nginx
    apt: pkg=nginx state=present
  - name: Copy matrix.conf to server
    copy:
      src: "{{ matrixConfFileToSend }}"
      dest: "/etc/nginx/conf.d/"
    notify:
      - restart nginx
  - name: Changes in matrix.conf
    lineinfile:
      path: /etc/nginx/conf.d/matrix.conf
      regexp: "{{ item.regexp }}"
      state: present
      line: "{{ item.line }}"
    with_items:
      - {regexp: 'server_name my.site.com;', line: '    server_name "{{ hostname }}"'}
      - {regexp: 'ssl_certificate     /etc/letsencrypt/live/my.site.com/fullchain.pem;', line: '    ssl_certificate     /etc/letsencrypt/live/{{ hostname }}/fullchain.pem;'}
      - {regexp: 'ssl_certificate_key /etc/letsencrypt/live/my.site.com/privkey.pem;', line: '    ssl_certificate_key /etc/letsencrypt/live/{{ hostname }}/privkey.pem;'}
    notify:
      - restart nginx
  - import_tasks: certs.yml
